
services:
  mlflow:
    build:
      context: .
      dockerfile: docker/Dockerfile.mlflow
    image: aqi-mlflow:latest
    container_name: mlflow-server
    env_file:
      - .env
    ports:
      - "5000:5000"      
    command:
      - mlflow
      - server
      - --backend-store-uri
      - ${MYSQLURL} #local mysql, host.docker.internal to specifiy machine host
      - --default-artifact-root
      - wasbs://mlflow@yubikaqidata.blob.core.windows.net/ #azure blob storage
      - --host
      - 0.0.0.0
      - --allowed-hosts
      - "*"
      - --port
      - "5000"
    networks:
      - aqi_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://0.0.0.0:5000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    mem_limit: 1g
    memswap_limit: 1g

  trainer:
    build:
      context: .
      dockerfile: docker/Dockerfile.trainer
    image: aqi-trainer:latest
    env_file:
      - .env
    volumes:
      - ./data:/data
      - ./models:/models
      - optuna-db:/optuna/db
    environment:
      - OPTUNA_STORAGE=sqlite:///optuna/db/optuna.db
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      mlflow:
        condition: service_healthy
    networks:
      - aqi_network
    profiles:
      - manual
    mem_limit: 3g
    memswap_limit: 3g

networks:
  aqi_network:
    driver: bridge
volumes:
  optuna-db:
    driver: local
