[metadata]
name = pypipeline
version = 0.0.0
author = Yubik Nakarmi
license = MIT

[options]
package_dir =
    = src
packages = find:
install_requires =
    pandas
    numpy
    scikit-learn
    mlflow
    pymysql
    xgboost
    



[options.packages.find]
where = src

[options.entry_points]
console_scripts =
    aqi-ingest = scripts.ingestion_hourly:main
    aqi-train  = scripts.train:main
    data_hourly_preprocessing = modules.data_hurly_preprocessing:main


