From python:3.9-slim

WORKDIR /frontend
RUN pip install --no-cache-dir mlflow pandas streamlit
COPY . .

EXPOSE 8501
CMD ["streamlit", "run", "app.py", "--server.address=0.0.0.0", "--server.port=8501"]