FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/* && pip install --upgrade pip


RUN pip install --no-cache-dir \
    mlflow \
    xgboost \
    pandas \
    pymysql

COPY src/ ./src/
COPY pyproject.toml setup.cfg ./

RUN pip install --no-cache-dir -e .

COPY ./hourly_pred_pipeline ./hourly_pred_pipeline

ENV PYTHONUNBUFFERED=1