FROM python:3.11-slim

WORKDIR /mlflow

RUN apt-get update && apt-get install -y --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip && \
    pip install --no-cache-dir \
    mlflow[aws,azure,gcp] \
    azure-storage-blob \
    azure-identity\
    pymysql \
    



